[tool.poetry]
name = "school management system"
version = "0.1.0"
description = ""
authors = ["quentalt <quentin.altieri@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
